export const render = (keyword: string, data: any) => {
  const title = `${keyword} - CPA Niche Scout AI Analysis`;
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { font-family: system-ui; background: #0b1220; color: #e6e9f0; margin: 0; padding: 20px; }
    .container { max-width: 900px; margin: 0 auto; }
    h1 { color: #4f7cff; margin-bottom: 10px; }
    .card { background: #121c3d; border: 1px solid #2b3a6a; border-radius: 8px; padding: 20px; margin: 20px 0; }
    .metric { display: inline-block; margin-right: 30px; }
    .metric-label { color: #a8adb8; font-size: 0.9rem; }
    .metric-value { color: #7a9eff; font-size: 1.5rem; font-weight: bold; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 0.85rem; margin: 5px 5px 5px 0; }
    .badge-build { background: rgba(16,185,129,0.2); color: #10b981; }
    .badge-watch { background: rgba(245,158,11,0.2); color: #f59e0b; }
    .badge-skip { background: rgba(239,68,68,0.2); color: #ef4444; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #2b3a6a; }
    th { background: #1a2847; font-weight: 600; }
  </style>
</head>
<body>
  <div class="container">
    <h1>${title}</h1>
    <p>Generated by CPA Niche Scout AI</p>
    
    <div class="card">
      <h2>Keyword Analysis</h2>
      <div class="metric">
        <div class="metric-label">Keyword Score</div>
        <div class="metric-value">${data.score || 'N/A'}</div>
      </div>
      <div class="metric">
        <div class="metric-label">Difficulty</div>
        <div class="metric-value">${data.difficulty || 'N/A'}</div>
      </div>
      <div class="metric">
        <div class="metric-label">Profit Potential</div>
        <div class="metric-value">${data.profit || 'N/A'}</div>
      </div>
    </div>
    
    <div class="card">
      <h2>Recommendation</h2>
      <span class="badge badge-${data.verdict === 'BUILD' ? 'build' : data.verdict === 'WATCH' ? 'watch' : 'skip'}">
        ${data.verdict || 'ANALYZE'}
      </span>
    </div>
    
    <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #2b3a6a; text-align: center; color: #a8adb8; font-size: 0.9rem;">
      <p>CPA Niche Scout AI v2.0 | Analysis Report</p>
    </footer>
  </div>
</body>
</html>`;
};
